version: "3.8"
services:
  app:
    container_name: prod 
    command:  bash -c "gunicorn fsd_medic.asgi:application --bind 0.0.0.0:8000  -k uvicorn.workers.UvicornWorker"

    build: .  
    ports:
      - "8000:8000"
    links:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
  grafana: 
    image: grafana/grafana
    ports: 
      - "3000:3000"
#db:
#   image: mysql
#   restart: always
#   ports:
#     - '3307:3306'
#   environment:

        #     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
