version: "3.8"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  memcached:
    image: memcached:latest
#db:
#   image: mysql
#   restart: always
#   ports:
#     - '3307:3306'
#   environment:

        #     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
