version: "3.8"
services:
  app:
    container_name: app
    command: >
      sh -c   "python manage.py makemigrations && 
              python manage.py migrate && 
              python manage.py runserver 0.0.0.0:8000"
    build: .
    ports:
      - '8000:8000'
    restart: always
    depends_on:
      - db
    links:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  db:
    image: mysql
    restart: always
    ports:
      - '3307:3306'
    environment:

      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
