version: "3.8"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml

    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
      #db:
#   image: mysql
#   restart: always
#   ports:
#     - '3307:3306'
#   environment:

        #     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
